### PR TITLE
Fix media blob handling (#11)

### PR DESCRIPTION
**Pull request by sam131102**
- Replaced base64 embedding of media files with URL.createObjectURL
- Media files are now handled in-memory, using temporary URLs.
- Fixes the performance issue highlighted in #11.

### CODE REVIEW

**Review by ianrandmckenzie — CHANGES_REQUESTED** [review]
Looks good, @sam131102 . I added the missing input back. One issue, though, the writing seems too temporary. If I close the tab and go back to editing from clicking "edit" on the dashboard, our images are gone.

Is there some kind of middleground we can reach with this?

**Comment by sam131102** [comment]
Keep the current code as of now which saves files temporarily and try using an external service for media along with an option to choose an offline mode to store it locally as well

**Review by ianrandmckenzie — CHANGES_REQUESTED** [review]
I think I am a bit confused by how this works, can you elaborate? Also, I see functions that are never called like `displayMediaFromIndexedDB`. Perhaps you can show it to me in our call today

**Review by ianrandmckenzie — APPROVED** [review]
Merging, but remember to add some code that deletes the image from localStorage after it is confirmed to exist in IndexedDB

**Pull request merged**
